services:
  api:
    image: ghcr.io/tawmy/dutyfinderservice:main
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reverse-proxy
    labels:
      caddy: duty-finder-service.eorzea.online
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse-proxy:
    external: true