services:
  api:
    image: dutyfinderservice
    build:
      context: .
      dockerfile: DutyFinderService/Dockerfile
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Debug
      LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: Debug
    labels:
      - dev.orbstack.domains=duty-finder-service.local
  
  db:
    labels:
      - dev.orbstack.domains=db.duty-finder-service.local
