services:
  api:
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: duty-finder-service.eorzea.online
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  reverse-proxy:
    external: true