services:
  api:
    image: ghcr.io/tawmy/dutyfinderservice:0.1.0
    container_name: duty-finder-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      LOGGING__LOGLEVEL__DEFAULT: Information
      LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: Warning
